
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async greet(name: string) : Promise<string> {
    return await TAURI_INVOKE("greet", { name });
},
/**
 * Receives the current set of selected node IDs from the frontend.
 * Stores them and returns the total count (placeholder for future stat calculations).
 */
async updateSelectedNodes(nodeIds: number[]) : Promise<Result<BuildStats, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_selected_nodes", { nodeIds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Receives the build info from the frontend.
 */
async updateBuildInfo(level: number, characterClass: Class, bloodline: Bloodline) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_build_info", { level, characterClass, bloodline }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAvailableTreeVersions() : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_available_tree_versions") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async loadTreeVersion(version: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_tree_version", { version }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTreeJson() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_tree_json") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Returns a lightweight summary of every gem for the frontend selector.
 */
async getGemList() : Promise<Result<GemSummary[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_gem_list") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Returns all skill groups for the current build.
 */
async getSkillGroups() : Promise<Result<SkillGroup[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_skill_groups") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Creates a new empty skill group and returns it.
 */
async createSkillGroup(label: string) : Promise<Result<SkillGroup, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_skill_group", { label }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Deletes a skill group by ID.
 */
async deleteSkillGroup(groupId: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_skill_group", { groupId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Adds a gem to a skill group. Validates the gem ID exists, builds a GemInstance with computed stats.
 */
async addGemToGroup(groupId: number, gemId: string) : Promise<Result<SkillGroup, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_gem_to_group", { groupId, gemId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Removes a gem from a skill group by its index in the gem list.
 */
async removeGemFromGroup(groupId: number, gemIndex: number) : Promise<Result<SkillGroup, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_gem_from_group", { groupId, gemIndex }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Updates the level and/or quality of a gem in a skill group, recomputing its stats.
 */
async updateGemLevelQuality(groupId: number, gemIndex: number, level: number, quality: number) : Promise<Result<SkillGroup, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_gem_level_quality", { groupId, gemIndex, level, quality }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Returns the skill group with up-to-date effects and compatibility.
 */
async getGroupEffects(groupId: number) : Promise<Result<SkillGroup, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_group_effects", { groupId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Returns all modifiers in the ModDB for the debug page, grouped by layer.
 */
async getDebugStats() : Promise<Result<DebugStatsResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_debug_stats") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type Bloodline = "None" | "Aul" | "Breachlord" | "Catarina" | "Delirious" | "Farrul" | "KingInTheMists" | "Lycia" | "Olroth" | "Oshabi" | "Primalist" | "Trialmaster" | "Warden" | "Warlock"
export type BuildStats = { total_strength: number; total_dexterity: number; total_intelligence: number; node_count: number; life: number; mana: number }
export type Class = { class: "Marauder"; ascendancy: MarauderAscendancy | null } | { class: "Ranger"; ascendancy: RangerAscendancy | null } | { class: "Witch"; ascendancy: WitchAscendancy | null } | { class: "Duelist"; ascendancy: DuelistAscendancy | null } | { class: "Templar"; ascendancy: TemplarAscendancy | null } | { class: "Shadow"; ascendancy: ShadowAscendancy | null } | { class: "Scion"; ascendancy: ScionAscendancy | null }
/**
 * A fully computed stat value (base × inc × more).
 */
export type DebugComputedStat = { base: number; inc: number; more: number; total: number }
/**
 * A single modifier entry for the debug page.
 */
export type DebugModEntry = { stat: string; mod_type: string; value: number; source: string; flags: string }
/**
 * All modifiers from each ModDB layer, for the debug page.
 */
export type DebugStatsResponse = { tree_mods: DebugModEntry[]; class_mods: DebugModEntry[]; computed: Partial<{ [key in string]: DebugComputedStat }> }
export type DuelistAscendancy = "Slayer" | "Gladiator" | "Champion"
/**
 * Gem color based on attribute tags.
 */
export type GemColor = "red" | "green" | "blue" | "white"
/**
 * A gem placed in a socket group — tracks identity, level, quality, and computed stats.
 */
export type GemInstance = { gem_id: string; name: string; is_support: boolean; level: number; quality: number; enabled: boolean; 
/**
 * Computed stats at the current level/quality (stat_id → value).
 */
stats: Partial<{ [key in string]: number }>; mana_cost: number | null; crit_chance: number | null; damage_effectiveness: number | null; mana_multiplier: number | null; cooldown: number | null; attack_speed_multiplier: number | null }
/**
 * Lightweight summary for the frontend gem selector dropdown.
 */
export type GemSummary = { id: string; name: string; tag_string: string; is_support: boolean; color: GemColor; description: string | null }
export type MarauderAscendancy = "Juggernaut" | "Berserker" | "Chieftain"
export type RangerAscendancy = "Raider" | "Deadeye" | "Pathfinder"
export type ScionAscendancy = "Ascendant"
export type ShadowAscendancy = "Assassin" | "Saboteur" | "Trickster"
/**
 * A group of linked gems — one active skill plus its supports.
 */
export type SkillGroup = { id: number; label: string; gems: GemInstance[]; enabled: boolean; 
/**
 * Support compatibility entries (only populated on analysis).
 */
compatibility: SupportCompatEntry[] }
/**
 * Whether a support gem is compatible with a specific active gem.
 */
export type SupportCompatEntry = { support_gem_id: string; active_gem_id: string; compatible: boolean }
export type TemplarAscendancy = "Inquisitor" | "Hierophant" | "Guardian"
export type WitchAscendancy = "Necromancer" | "Occultist" | "Elementalist"

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
